[project]
name = "cmd-k"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "openai>=1.0.0",
    "toml>=0.10.0",
]

[project.scripts]
cmd-k = "cmd_k:main"

[tool.uv]
package = true
